version: '1.0.{build}'

os: Visual Studio 2015

platform:
  - Win32

configuration:
  - Debug
  - Release

init:
  cmd: cmake --version

clone_folder: C:\projects\Hermes

before_build:
  - cmd: cd C:\projects\Hermes
  - cmd: md build
  - cmd: cd build
  - cmd: cmake ..

build: off

test: off
